import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "1rem", screens: { "2xl": "1400px" } },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        "border-strong": "hsl(var(--border-strong))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        "background-2": "hsl(var(--background-2))",
        "background-3": "hsl(var(--background-3))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          glow: "hsl(var(--primary-glow))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        success: "hsl(var(--success))",
        warning: "hsl(var(--warning))",
        rose: "hsl(var(--rose))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 4px)",
        sm: "calc(var(--radius) - 8px)",
      },
      backgroundImage: {
        "gradient-primary": "var(--gradient-primary)",
        "gradient-bg": "var(--gradient-bg)",
        "gradient-card": "var(--gradient-card)",
        "gradient-warm": "var(--gradient-warm)",
      },
      boxShadow: {
        glow: "var(--shadow-glow)",
        soft: "var(--shadow-soft)",
        card: "var(--shadow-card)",
      },
      animation: {
        "card-entry": "cardEntry .55s cubic-bezier(.2,.9,.3,1.2) both",
        "slide-up": "slideInUp .4s ease-out both",
        "slide-down": "slideInDown .4s ease-out both",
        "slide-left": "slideInLeft .4s ease-out both",
        "slide-right": "slideInRight .4s ease-out both",
        "pop-in": "popInBig .5s cubic-bezier(.2,.9,.3,1.4) both",
        "tag-bounce": "tagBounce .4s cubic-bezier(.2,.9,.3,1.4) both",
        "bubble-in": "bubbleIn .35s cubic-bezier(.2,.9,.3,1.3) both",
        "bubble-in-me": "bubbleInMe .35s cubic-bezier(.2,.9,.3,1.3) both",
        "sheet-up": "sheetUp .35s cubic-bezier(.2,.9,.3,1) both",
        "heart-beat": "heartBeat 1.2s ease-in-out infinite",
        glow: "glow 2.4s ease-in-out infinite",
        "pulse-dot": "pulseDot 1.6s ease-out infinite",
        "float-up": "floatUp 3s ease-in-out infinite",
        "float-up-sm": "floatUpSm 2.4s ease-in-out infinite",
        "wave-bar": "waveBar .8s ease-in-out infinite",
        "particle-float": "particleFloat 8s linear infinite",
        "logo-pulse": "logoPulse 2.4s ease-in-out infinite",
        "spin-slow": "spinSlow 8s linear infinite",
        breathe: "breathe 3s ease-in-out infinite",
        "like-float": "likeFloat .9s ease-out forwards",
        confetti: "confettiFall 1.6s ease-in forwards",
        shimmer: "shimmer 2s linear infinite",
        typing: "typing 1.2s ease-in-out infinite",
        "accordion-down": "accordion-down .2s ease-out",
        "accordion-up": "accordion-up .2s ease-out",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
